### ISSUE TITLE
Chart not Building

### ISSUE THREAD

**Issue by sherlocktech** [sherlocktech/fundamental-analysis-teacher#16]
In `getQuandlInfo(company)` `companyInfo` is created:

``` javascript
var timeseries = new Timeseries();
var price = new Price();
var fundamentals = new Fundamentals();
var companyInfo = new CompanyInfo(timeseries, price, fundamentals);

...

function CompanyInfo(timeseries, price, fundamentals) {
    this.timeseries = timeseries;
    this.price = price;
    this.fundamentals = fundamentals;
}

...

return companyInfo;
```

The `Timeseries` object which only contains a couple arrays:

``` javascript
//get request from query, result is stored into timeseries arrays
var stockReq = $.getJSON(query, function( result ) {
//on each element in the data array push the date and price to respective array
$.each(result.dataset_data.data, function ( index, subarray ) {
  timeseries.date.push(subarray[0]);
  timeseries.price.push(subarray[4]);
});
```

However, for some reason c3 doesn't like it:

``` javascript
var buildStockHistoryChart = function( timeseries ) {
  var date  = timeseries.date;
  var price = timeseries.price;

  var chart = c3.generate({
      bindto: '#stock_history',
      data: {
        x: 'date',
        columns: [
          date,
          price
        ]
      },
      axis: {
        x: {
          text: 'Date',
          type: 'timeseries'
        },
        y:'Closing Price'
      }
  });
};
```

Here is what the chart is building now:
<img width="389" alt="screen shot 2016-04-10 at 7 00 29 pm" src="https://cloud.githubusercontent.com/assets/5942366/14414938/9639825a-ff4e-11e5-83db-4884fbea2ffd.png">
I'll reference this from the commit in debug branch.

**Comment by ehaughee** [comment]
This is what I see:
<img width="391" alt="screen shot 2016-04-11 at 10 14 46 pm" src="https://cloud.githubusercontent.com/assets/312189/14450429/16708808-0033-11e6-85a2-5bcd3af196a1.png">

Seems to be working.

**Comment by sherlocktech** [comment]
@ehaughee are you using the debug branch? That is the branch with the most up to date changes (see [b1f5a44](https://github.com/sherlocktech/fundamental-analysis-teacher/commit/b1f5a4433224e9161c340b0fcf68bf189a3a8ac1)). The [link](http://sherlocktech.github.io/fundamental-analysis-teacher/) in the repo description will always be working because I do not add feature to the gh-pages branch unless they are working. Similarly, I am trying to keep the master branch clean of bugs. 

If you have a suggestion as to how best use git, I'm all ears. I was trying to use multiple branches as a "git best practice", but let me know if they aren't usually used this way.

**Comment by ehaughee** [comment]
@sherlocktech Ahh I'll try the dev branch.  I just didn't notice this was a bug specifically related to the dev branch.

**Comment by ehaughee** [comment]
Ok the issue is because you receive your data in an asynchronous call back but don't use it there.  The easiest way to show what I mean is to put two breakpoints (using Chrome dev tools or whatever) in `app.js` on lines [6](https://github.com/sherlocktech/fundamental-analysis-teacher/blob/debug/app.js#L6) and [7](https://github.com/sherlocktech/fundamental-analysis-teacher/blob/debug/app.js#L7).  And then place a breakpoint in `getQuandlInfo.js` on line [28](https://github.com/sherlocktech/fundamental-analysis-teacher/blob/debug/res%2Fjs%2FgetQuandlInfo.js#L28).

You will see that the breakpoints get hit in the following order:
1. [app.js#6](https://github.com/sherlocktech/fundamental-analysis-teacher/blob/debug/app.js#L6)  
   No explanation necessary.
2. [app.js#7](https://github.com/sherlocktech/fundamental-analysis-teacher/blob/debug/app.js#L7)  
   Then this line gets hit immediately despite the call to `$.getJSON` inside `getQuandlInfo.js`.  The reason is that the `getJSON` call is asynchronous and returns its data into a callback (or the done promise) _when it is received_.
3. [getQuandlInfo.js#28](https://github.com/sherlocktech/fundamental-analysis-teacher/blob/debug/res%2Fjs%2FgetQuandlInfo.js#L28)  
   Now we hit this breakpoint as we have received the data.

So what's happening is you are trying to build the chart with no data because the request to get the data from the API returns after you try to build the c3 chart.

Let me know if you need any additional information on how to restructure your application/data flow.

**Comment by sherlocktech** [comment]
Thank you very much. You helped me learn about Chrome's debugging tools. This made sense to me as soon as I read your explanation. I have seen this mistake before in school so I knew what I was looking for when you pointed me in the right direction.

The reason I restructure the code like this in the first place was because I wanted to make it more modular. I thought that breaking up the system into different files was a good but I didn't think of the repercussions. I'll open another issue (#21) to discuss how best to structure my code.
